version: 2.1

jobs:
  udagram-app:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed phucle7/udagram-api-feed:v11
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user phucle7/udagram-api-user:v11
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend phucle7/udagram-frontend:v11
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy phucle7/udagram-reverseproxy:v11
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push phucle7/udagram-api-feed:v11
            docker push phucle7/udagram-api-user:v11
            docker push phucle7/udagram-frontend:v11
            docker push phucle7/udagram-reverseproxy:v11
workflows:
  default:
    jobs:
      - udagram-app
      - build-docker:
          requires: [udagram-app]
