version: 2.1

jobs:
  project3-app:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed longtran020299/udagram-api-feed:v1
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user longtran020299/udagram-api-user:v1
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend longtran020299/udagram-frontend:v1
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy longtran020299/udagram-reverseproxy:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push longtran020299/udagram-api-feed:v1
            docker push longtran020299/udagram-api-user:v1
            docker push longtran020299/udagram-frontend:v1
            docker push longtran020299/udagram-reverseproxy:v1
workflows:
  default:
    jobs:
      - project3-app
      - build-docker:
          requires: [project3-app]
